---
abstract: "Manage Honeydew's nightly queue functionality"
author:
  - 'Daniel Gempesaw <gempesaw@gmail.com>'
build_requires:
  DBD::Mock: '0'
  File::Basename: '0'
  File::Temp: '0'
  Redis: '0'
  Test::More: '0'
  Test::RedisServer: '0'
  Test::Spec: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.036, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Honeydew-Queue
requires:
  Cwd: '0'
  DBD::mysql: '0'
  DBI: '0'
  DDP: '0'
  File::Spec: '0'
  Getopt::Long: '0'
  Honeydew::Config: '0'
  Honeydew::ExternalServices::Crontab: '0'
  Moo: '0'
  Resque: '0'
  Try::Tiny: '0'
  feature: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/honeydew-sc/Honeydew-Queue/issues
  homepage: https://github.com/honeydew-sc/Honeydew-Queue
  repository: https://github.com/honeydew-sc/Honeydew-Queue.git
version: '0.06'
